punchat:
  admin:
    email: ${ADMIN_EMAIL}
spring:
  cloud:
    stream:
      bindings:
        inviteToWorkspaceEvents:
          destination: events.invitation.workspace
          content-type: application/json
        accessCodeGeneratedEvents:
          destination: events.accesscode.generated
          content-type: application/json
