spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mailUsername:punchat.application@gmail.com}
    password: ${mailPassword:OdEOrshebVeytc0}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    stream:
      bindings:
        newEmailsEvents:
          destination: events.emails.created
          group: emails-senders-group
          durableSubscription: true
          content-type: application/json
