zuul:
  routes:
    id:
      path: /id/**
      serviceId: id
    uaa:
      path: /uaa/**
      serviceId: uaa
    messaging:
      path: /messaging/**
      serviceId: messaging
spring:
  cloud:
    stream:
      default-binder: consul
