spring:
  cloud:
    stream:
      bindings:
        accountCreatedEvents:
          destination: events.users.created
          group: messaging-group
          durableSubscription: true
          content-type: application/json
