spring:
  cloud:
    stream:
      bindings:
        accountCreatedEvents:
          destination: events.users.created
          group: messaging-group
          durableSubscription: true
          content-type: application/json
        inviteToChannelEvents:
          destination: events.invitation.channel
          content-type: application/json
        newMemberInChannel:
          destination: events.channel.member.created
          content-type: application/json
        newBroadcastMessageEvents:
          destination: events.channel.broadcast.messages.created
          content-type: application/json
